### ISSUE TITLE
Persist weather file location

### ISSUE THREAD

**Issue by Myoldmopar** [NREL/EP-Launch#106]
This would just be a convenience.  When you select a weather file, remember it as the last file path you've selected.  Then when you re-open a "file open" dialog for selecting weather, just start with the most recent path.  This doesn't necessarily need to be persisted between sessions, but it should be initialized to something meaningful -- maybe the currently selected directory in the tree control.

**Comment by JasonGlazer** [comment]
@Myoldmopar on Windows it comes up with the last used path when the WeatherDialog's FindOnDisk button is pressed. It remembers this between sessions. Please check if this is occurring also on Linux. If so, I think we can close this issue.
