### ISSUE TITLE
Handle Version Confusion of 9.0.0 and 9.0.1

### ISSUE THREAD

**Issue by JasonGlazer** [NREL/EP-Launch#109]

**Comment by JasonGlazer** [comment]
@Myoldmopar or @mjwitte can one of you flesh out this issue. I'm not sure what the problem is with the version updating.

**Comment by Myoldmopar** [comment]
Yes, once we've got a handle on it from the E+ side I will be able to do the EP-Launch changes accordingly.  I'm assuming Monday...but we'll see this weekend.

**Comment by Myoldmopar** [comment]
Fixed with #110, though the fixes to the transition.py workflow file to make it cross-platform-able are in-waiting over at E+, to be released with the next version.  The transition works perfectly fine on windows though.
