### ISSUE TITLE
Selecting from Weather menu does not show weather in weather column

### ISSUE THREAD

**Issue by JasonGlazer** [NREL/EP-Launch#113]

**Comment by Myoldmopar** [comment]
It updates for me using both the toolbar button and selecting it from the menu bar at the top.  Can you confirm and elaborate?

**Comment by JasonGlazer** [comment]
I should have said "selecting from recent or favorite weather files menu items..."

**Comment by JasonGlazer** [comment]
@Myoldmopar now that this is cleared, do you think we are ready for another draft release?
