### ISSUE TITLE
Modify EP-Launch crash handling when eplusout.end is turned off

### ISSUE THREAD

**Issue by mjwitte** [NREL/EP-Launch#126]
The new v9.4.0 OutputControl:Files object allows the user to disable the eplusout.end file. Both EP-Launch and EP-Launch3 assume that the simulation has crashed if there is no eplusout.end file and issues a message to that effect. So, EP-Launch needs to either mention this possibility in the warning message, or read the last line of the err output file to determine is there was a crash (eplusout.err is not optional, it is always produced).

See discussion in https://github.com/NREL/EnergyPlus/pull/8250 .

**Comment by JasonGlazer** [comment]
It looks like EP-Launch 3 is not using the .end file to detect crashes.
