### ISSUE TITLE
Naming convention

### ISSUE THREAD

**Issue by Myoldmopar** [NREL/EP-Launch#14]
Right now there are quite a few places where EP-Launch **3** has crept in, including the name of the cache files and other stuff.  This issue is more of a question.  Do we want that?  I think there are pros and cons to it.  If we think something will persist through multiple versions of the tool, then keeping a 3 in there might make it confusing it we go to version 4 later and want to reuse those resources.  But then again, there might be things we want to actually change heavily during a major version change, so putting a 3 on there might be the right move.

In general, this is just an issue to have a little conversation and then we can be very intentional about it as we develop new things.

**Comment by JasonGlazer** [comment]
I think we want to make it EP-Launch without a 3 throughout the code. If we have major version changes in the future we can decide at that point if something should be shown as tied to a version number.

**Comment by Myoldmopar** [comment]
At a minimum, I think we need to change the name of the cache file.  It's a one-line change in the code, but it will then mean that any directories you or I have locally will be cleared due to the new expected filename.  I'll start a branch today/this weekend that cleans this and the last remaining Beta issues, and we should be getting really close.  Maybe we could put the Beta out next week for a 2 week testing window, fix anything that comes up, and maybe be ready to call it version 1.0 by September 30?
