### ISSUE TITLE
Workflow choice dropdown doesn't look right on Mac

### ISSUE THREAD

**Issue by Myoldmopar** [NREL/EP-Launch#28]

**Comment by JasonGlazer** [comment]
Here is the image from the latest installer version of EP-Launch beta
![image](https://user-images.githubusercontent.com/2582150/45056826-9e58d580-b059-11e8-9923-7b77eb5aff13.png)

**Comment by JasonGlazer** [comment]
I actually tried to change the .py file that is part of the Mac application yesterday to do just that and it didn't seem to work. Maybe the Python interpreter doesn't re-read those files if they are part of the Mac application package.

**Comment by Myoldmopar** [comment]
That's a possibility.  But I've at least seen confirmation that the floaty-behind thing is reproducible, so I will, for now, assume that the alternative (without workaround) is also occurring.  If you get a chance to test out the code from a development environment (as opposed to the installer package), it would be great to verify fully.

**Comment by Myoldmopar** [comment]
Closed via #70
