### ISSUE TITLE
Need to add automated packaging support

### ISSUE THREAD

**Issue by Myoldmopar** [NREL/EP-Launch#29]
All platforms - test fully.

### Linux
- [x] `python setup.py build` passes
- [x] Package runs on local machine
- [x] Integrated into Travis
- [x] Downloaded package runs on dev machine
- [x] Downloaded package runs on bare machine

### Mac
- [X] `python setup.py bdist_mac` passes
- [X] Package runs on local machine
- [x] Integrated into Travis
- [x] Downloaded package runs on dev machine
- [x] Downloaded package runs on bare machine

### Windows
- [x] ~~`python setup.py build` passes~~
- [x] ~~Package runs on local machine~~
- [x] `python setup.py bdist_msi` passes
- [x] Integrated into AppVeyor
- [x] Downloaded package runs on dev machine
- [x] Downloaded package runs on bare machine

**Comment by Myoldmopar** [comment]
@JasonGlazer OK, could you try running `python setup.py bdist_msi` on your machine?  It is supposed to make a super simple msi installer...right from `cx_freeze`.  I now having it create a proper Mac .app package from `cx_freeze` without any significant changes to the code.

**Comment by JasonGlazer** [comment]
That seemed to work. It creates a new "dist" folder in the repo with a EP-Launch-0.1-amd64.msi file. When I double click on it acts like an installer. I did not finish the install because I didn't want to mess anything else. Do you want the file?

**Comment by JasonGlazer** [comment]
I put the file on the release tag we used earlier.

**Comment by Myoldmopar** [comment]
So Travis doesn't like Python 3.6 on Mac.  There is a way, but it's not fun.  More info here: https://pythonhosted.org/CodeChat/.travis.yml.html

I'll consider trying it later, but for now I can run `setup.py bdist_mac` and post it.

**Comment by Myoldmopar** [comment]
Barebones Linux machine did not like the built package.  Missing zlib it said.  I think I tracked it down to the fact that it is missing the zlib dev package on Travis, and it quietly missed that dependency.  I added it to Travis, I'll trigger a tag of my bug fix branch, and I'll retry.

**Comment by Myoldmopar** [comment]
The current problem is that pubsub.pub isn't being found in the package, because it's not being included during the build process.  I believe it's a problem where wx defines its own pubsub and then we have the main pypubsub.  I have tried a few things, but I need to step back and create a fresh branch where I can clearly see my approach and clearly test it out in an isolated manner.

Other thoughts:
- I'm starting to think that we'll need to carefully limit which version of Linux we will support.  I think maybe just build on 18.04 and only support 18.04.  That would ensure we get the right versions of libpng, glibc, etc.  We could possibly expand to other versions, but I don't know why we would really.
- For building 18.04, I can do it locally, or we can have Travis do it, but we'll need to start from a docker image since Travis doesn't have 18.04 images available by default.  We could create a nice Dockerfile that has some dependencies installed already to speed things up eventually too.
- I have VMs set up for barebones Ubuntu 18.04 and a relatively minimal Windows VM.  It would be nice to have a bare Mac and super-bare Windows VM to test on as well.  I need to carefully track progress of each test-release I make
- We need to include the target architecture, platform, platform version, and sha (#57) to the resulting package names to keep things straight

Links:
 - My cx freeze was coming up with a ZipImportError like [this](https://stackoverflow.com/questions/48288658/zipimport-zipimporterror-cant-decompress-data-zlib-not-available).  I added apt-get zlib* to the travis install and it **seemed** like that took care of it, but I need to do some tests to verify.
 - CX Freeze has a little [FAQ](http://cx-freeze.readthedocs.io/en/latest/faq.html) that includes a very minimal section about dependencies.  The freeze output still lists tons of potentially missing dependencies.  I would love to find a link that is like: "The process of identifying missing dependencies using cx Freeze, and how to find and include them in your package"
 - This [link](https://groups.google.com/forum/#!topic/pyinstaller/BsciphyIaw0) talks about the GLIBC mismatch, which is what makes me think we should target specific versions of Ubuntu.  We'll see.
 - [This](https://gatc.ca/2009/12/23/python-program-executables/) is the closest I've seen to a "tutorial" about fixing missing dependencies from a cxFreeze process.  Very helpful
 - [This](https://romanvm.pythonanywhere.com/post/using-docker-travis-continuous-integration-25/) is a page showing how they used the Ubuntu 16.04 Docker image on Travis.  It's helpful, but I still feel uncertain about how my scripts get executed and where I need to install dependencies, and how to use this with the build matrix that includes osx builds
 - PyPubSub has a [page](http://pypubsub.sourceforge.net/development/py2exe.html) showing how to create different setup files for different packaging tools.  They didn't directly work for me, but helpful anyway.
 - WxPython also has a [page](https://wiki.wxpython.org/CreatingStandaloneExecutables) showing how to get WxPython to work with packaging tools.  Again not directly helpful, but some info there.

Plans:
 - I may do a simple hello world repo where I use wx and cx freeze and see if I can get it working over there to really isolate the problem.

**Comment by Myoldmopar** [comment]
Closed via #60
