### ISSUE TITLE
Add indicator for stale output files

### ISSUE THREAD

**Issue by JasonGlazer** [NREL/EP-Launch#31]
Add an indicator to the main list that shows when the output files are older than the input file. This would indicate that the output files no longer reflect the input files and should be rerun. Maybe include columns in the list that show timestamps for the input files and output files. The stale indicator should probably be a column but perhaps even something more obvious like a change in color for the output file icons.

**Comment by Myoldmopar** [comment]
In addition we need to background get the file versions with this same "sweep"
