### ISSUE TITLE
FileNameMenus base class

### ISSUE THREAD

**Issue by Myoldmopar** [NREL/EP-Launch#33]
This looks like it was added with the idea of there being multiple derived classes.  @JasonGlazer could you confirm that and confirm whether we need it or not?  As I'm working on the cache work, I'm also trying to simplify and reduce the code wherever possible.  I'd like to just move that class to a single file instead of the base class and extra folder structure.  Thanks!

**Comment by JasonGlazer** [comment]
Yes, I thought it might be more generic but it hasn't turned out that way. It can be simplified.

**Comment by Myoldmopar** [comment]
Closed via #24
