### ISSUE TITLE
Folder and Weather Menus allow more than one file shown as selected

### ISSUE THREAD

**Issue by JasonGlazer** [NREL/EP-Launch#36]
I think this is an old issue. Certain sequences of selecting files seem to allow showing more than one file selected at a time which should not occur.

**Comment by Myoldmopar** [comment]
@JasonGlazer I'm happy to try to peek at this, but I don't really have enough info to replicate.  I could monkey test with it, but I wouldn't do that until I know that's what I need to do.

**Comment by JasonGlazer** [comment]
@Myoldmopar when multiple items were on the folder or weather recently used or favorites part of the menu only one item should be selected and if that items appears in the other section (recent or favorite) it should also be checked. Sometimes, weirdly two items would remain checked. It seemed to happen when it was the first or last item I think so that made me wonder if some indexing to clear the menu was wrong.

**Comment by JasonGlazer** [comment]
To reproduce
Remove the setti

1. ngs file (in Windows use Regedit to remove the setting).
2. Start EP-launch, the weather menu should have no recent files
3. Select an EnergyPlus IP idf workflow
4. Select an IDF file
5. Using Weather .. Select, choose an EPW file. Repeat this two times more with different EPW files, There should be three items on the recent menu
6. Exit EP-Launch
7. Restart EP-Launch
8. Select the IDF file
9. Using Weather .. Select, choose an EPW file. There should be four items on the recent menu
10. Using the Weather menu select the third weather file under recent
11. Using the weather menu select the fourth weather file under recent
12. The third and fourth item shou

ld both be shown as selected which is wrong

**Comment by Myoldmopar** [comment]
Fixed in #110
