### ISSUE TITLE
Consider Version Stuff

### ISSUE THREAD

**Issue by Myoldmopar** [NREL/EP-Launch#48]
So, given the major time crunch, I want to have a candid discussion about the E+ version-specific nature of some of the code.  And by that, I really mean the down-selecting workflows for a specific version.  For the beta release, users will likely have no workflows except the "built-in" ones until they drop some manually into an install of E+ 8.9 or something.  For the 1.0 release, users will likely have any built-in ones plus the ones that will come packaged with 9.0.  For the releases beyond that, they will start having more than one "set" of workflows.  It seems to me that our time might be optimized if we kinda roll back away from some of that extra bookkeeping and management and just let that list be the full list of all workflows.  Then we can properly design out the workflow "set" management and get it in there really nicely.  I know I have added some code in places on the frame that I think I could do a lot better if I had a better grasp of the version-specific code at times.

Anyway, just a suggestion for now to discuss.

**Comment by JasonGlazer** [comment]
Remember with #17 still open, all the workflows are showing and not just the ones related to the selected version.

**Comment by Myoldmopar** [comment]
Addressed in #81
