### ISSUE TITLE
Something Funny with no Output Files

### ISSUE THREAD

**Issue by Myoldmopar** [NREL/EP-Launch#54]
When I select a workflow that doesn't define any output files (I think that's the problem--I believe it happens with the silly built-in site:location workflow), there are a bunch of GTK warnings.  I think the toolbar is getting goofed up because it expects at least one or something.

**Comment by JasonGlazer** [comment]
I can't reproduce this. It is possible I fixed the issue with #19 since I fixed other items related to output files and workflows. @Myoldmopar please confirm that you are not seeing this issue?

**Comment by Myoldmopar** [comment]
I can't reproduce, we'll close this for now.
