### ISSUE TITLE
Still something funny with external programs

### ISSUE THREAD

**Issue by Myoldmopar** [NREL/EP-Launch#68]
Trying to open the "Text Editor" on my Linux box gave:

```
Traceback (most recent call last):
  File "eplaunch/interface/frame.py", line 1017, in handle_tb_text_editor
    self.external_runner.run_text_editor(full_path_name)
  File "eplaunch/interface/externalprograms.py", line 57, in run_text_editor
    subprocess.Popen([text_editor_binary, file_path])
  File "subprocess.py", line 709, in __init__
  File "subprocess.py", line 1344, in _execute_child
FileNotFoundError: [Errno 2] No such file or directory: 'libreoffice --writer ': 'libreoffice --writer '
```

**Comment by JasonGlazer** [comment]
is libreoffice --writer your default text editor?

**Comment by Myoldmopar** [comment]
Yeah but look carefully at the command line.  There's a trailing space after the `--writer ` argument.  Also, `libreoffice --writer` isn't the file anyway, `libreoffice` is, and `--writer` needs to be carefully applied as a separate command line argument to it.

**Comment by JasonGlazer** [comment]
Shouldn't you be using VI or emacs or something?

**Comment by Myoldmopar** [comment]
> Shouldn't you be using VI or emacs or something?

Of course I do!  But not when opening files from the desktop environment like this is trying to do... :laughing:
