### ISSUE TITLE
Copy latest workflow files to EnergyPlus repo pull request

### ISSUE THREAD

**Issue by JasonGlazer** [NREL/EP-Launch#75]

**Comment by Myoldmopar** [comment]
- [ ] Update the ones in the repo
- [ ] Add configuration on them so they include a version number
- [ ] Add install commands to add them to the package

**Comment by JasonGlazer** [comment]
@Myoldmopar do you know if there a way to have a link between the repos so that we don't need to copy the files?

**Comment by Myoldmopar** [comment]
No, but very soon we won't have these files in the EP-Launch repo at all.  They will only live in the EP repo, so there won't be copying going on after things stabilize.

**Comment by Myoldmopar** [comment]
This has been all done, and will be merged as https://github.com/NREL/EnergyPlus/pull/6957 once CI comes back entirely clean (it will).

We can keep the files in the EP-Launch repo for now, but at some point we'll have a PR to remove any EnergyPlus specific workflows from here.  I think we should develop a number of workflows that don't have to do with EnergyPlus to keep here in this repo and distribute with EP-Launch itself.

I'm going to go ahead and close this now that the files are over there in EP land.

**Comment by JasonGlazer** [comment]
Until we move it to the EP repo and remove it from here, we need to think about it anytime we update a workflow file.
