### ISSUE TITLE
Confusion about "All Files"

### ISSUE THREAD

**Issue by Myoldmopar** [NREL/EP-Launch#79]
With "all files" section open, if you click "Open in Text Editor", it's a bit unclear as to which file will open (it's the control list file that gets opened).

**Comment by JasonGlazer** [comment]
Maybe we should just disable "all files" for now. None of the buttons in the toolbar work when it is open. Either that or we should disable all the buttons.

**Comment by Myoldmopar** [comment]
I definitely support disabling it for now.  I can do that while I'm wrapping up the other stuff today.

**Comment by Myoldmopar** [comment]
Closed via #81
