### ISSUE TITLE
Output Toolbar Reordering

### ISSUE THREAD

**Issue by Myoldmopar** [NREL/EP-Launch#80]
So the output toolbar reordering dialog and everything seems really complex at this stage, especially since we aren't unit testing a majority of the UI code. Could we consider simplifying that menu item/dialog/capability?  We could always add i backt later.

**Comment by JasonGlazer** [comment]
The last time I checked it is working and is the only way for users to select which output files to look at since EnergyPlus has so many.

**Comment by Myoldmopar** [comment]
OK, you're right, it's working great and we should keep it in there.  I'll close this.
