### ISSUE TITLE
Workflow dropdown too narrow on Windows

### ISSUE THREAD

**Issue by JasonGlazer** [NREL/EP-Launch#82]
The dropdown list on windows is too narrow to display the entire contents of the list.
![image](https://user-images.githubusercontent.com/2582150/45549815-aac5f680-b7ee-11e8-9ba0-49c9a2daa383.png)

Or when it is open:

![image](https://user-images.githubusercontent.com/2582150/45549846-c3361100-b7ee-11e8-9c80-ccbdaf8ea923.png)

**Comment by JasonGlazer** [comment]
@Myoldmopar I assume you are going to fix this. Let me know if you need any help.

**Comment by Myoldmopar** [comment]
Yeah, I think it might just need an extra call to `.Realize()`.  While writing up the documentation around workflows I found a chunk of repeated code and tidied it up, but I think it might have moved the workflow dropdown populating until later.  I'll investigate today.

**Comment by Myoldmopar** [comment]
Closed via #81
