### ISSUE TITLE
Settings..Version.. menu is not listing versions

### ISSUE THREAD

**Issue by JasonGlazer** [NREL/EP-Launch#83]
This happened previously and is happening again.

**Comment by JasonGlazer** [comment]
@Myoldmopar I assume you are going to fix this, let me know if you need my help.

**Comment by JasonGlazer** [comment]
I believe this is also causing the EnergyPlus workflow to break because it is trying to run the "builtin" version instead of a local one.

**Comment by Myoldmopar** [comment]
Closed via #81
