### ISSUE TITLE
Weather file operation should be polished

### ISSUE THREAD

**Issue by Myoldmopar** [NREL/EP-Launch#89]
I think we've talked about this before; it just feels a bit funny how you select one and the effects aren't really clear to the user.

**Comment by JasonGlazer** [comment]
Conclusions from today's call:
- make a separate weather dialog box that has "design day", a list of recent files, and a way to choose a weather file
- the weather button pulls up this new weather dialog box
- if no file is selected when the run button is pressed the new weather dialog box is shown

Not discussed:
- should the "favorites" be accessed from this dialog?
- should the status bar bother showing the "active" weather file anymore?
- should the weather file menu be used anymore?

**Comment by JasonGlazer** [comment]
@Myoldmopar did I miss anything from our discussion?

**Comment by Myoldmopar** [comment]
Closed via #104
