### ISSUE TITLE
Can Transition just be a workflow?

### ISSUE THREAD

**Issue by Myoldmopar** [NREL/EP-Launch#9]
A lot of stuff in [this file](https://github.com/NREL/EP-Launch/blob/c9e5fb617241582d77c9f04dbb7946b559d97c3f/eplaunch/utilities/transitionversion.py) seems like it would be well-suited for just being a transition workflow.  If that were possible, it would reduce the complexity of EP-Launch as a whole for tracking versions, etc.  The transition workflow file would just belong to a specific version.  If we could even assume that the user would always want to update their file to the latest version, then that would be even simpler.  What do you think @JasonGlazer ?

**Comment by JasonGlazer** [comment]
We could make the transition a workflow but I think supporting multiple version updates is important since many people do not update their version of EnergyPlus that often. As far as tracking versions, I would still like the grid to show the file version number.

**Comment by JasonGlazer** [comment]
This was previously addressed by pull request #11
